const { getDb } = require('../config/db');
const bcrypt = require('bcryptjs');
const jwt = require('jsonwebtoken');

const register = async (req, res) => {
    const { name, email, password, role } = req.body;

    try {
        const db = getDb();
        const salt = await bcrypt.genSalt(10);
        const hashedPassword = await bcrypt.hash(password, salt);

        // 1. Insert User using image-based schema (UUID generated by default)
        const userResult = await db.query(
            'INSERT INTO users (display_name, email, hashed_password) VALUES ($1, $2, $3) RETURNING id',
            [name, email, hashedPassword]
        );
        const userId = userResult.rows[0].id;

        // 2. Assign Role (default to 'learner' if none provided)
        const roleName = role || 'learner';
        const roleResult = await db.query('SELECT id FROM roles WHERE name = $1', [roleName.toLowerCase()]);

        if (roleResult.rows[0]) {
            await db.query(
                'INSERT INTO user_roles (user_id, role_id) VALUES ($1, $2)',
                [userId, roleResult.rows[0].id]
            );
        }

        res.status(201).json({ message: 'User registered successfully', userId });
    } catch (error) {
        console.error('REGISTRATION ERROR:', error);
        if (error.code === '23505') {
            return res.status(400).json({ message: 'Email already exists' });
        }
        res.status(500).json({ message: 'Server error during registration' });
    }
};

const login = async (req, res) => {
    const { email, password } = req.body;

    if (!email || !password) {
        return res.status(400).json({ message: 'Email and password are required' });
    }

    try {
        const db = getDb();

        // Join with user_roles and roles to get the role name
        const result = await db.query(`
            SELECT u.*, r.name as role_name 
            FROM users u
            LEFT JOIN user_roles ur ON u.id = ur.user_id
            LEFT JOIN roles r ON ur.role_id = r.id
            WHERE u.email = $1
        `, [email]);

        const user = result.rows[0];

        if (!user) {
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        // Handle case where hashed_password might be missing or null
        if (!user.hashed_password) {
            console.error(`User ${email} has no hashed_password in database`);
            return res.status(500).json({ message: 'Account configuration error' });
        }

        const validPassword = await bcrypt.compare(password, user.hashed_password);
        if (!validPassword) {
            return res.status(401).json({ message: 'Invalid credentials' });
        }

        const token = jwt.sign(
            { id: user.id, email: user.email, role: user.role_name, name: user.display_name },
            process.env.JWT_SECRET,
            { expiresIn: '24h' }
        );

        res.json({
            token,
            user: {
                id: user.id,
                name: user.display_name,
                role: user.role_name
            }
        });
    } catch (error) {
        console.error('LOGIN ERROR:', error);
        res.status(500).json({ message: 'Server error during login' });
    }
};

module.exports = { register, login };
